### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by seraj** [cullenjett/react-ssr-boilerplate#18]
hi.
i just use this boilerplate for make my SPA ssr.
when i add my npm package and installed all of them i got this.
any idea about how can i fix this?

```
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/element-react/dist/npm/es5/src/table/TableHeader.js:48:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by lineldcosta** [comment]
try this https://github.com/lineldcosta/mobile-web

**Comment by seraj** [comment]
> try this https://github.com/lineldcosta/mobile-web

i can't underestand it! this is just a ripo with all react stuff!

**Comment by cullenjett** [comment]
Hi @seraj,

It looks like a library you are using (`element-react`) doesn't support server side rendering. Because SSR apps are first rendered on a server you have to avoid using browser APIs or handle it gracefully when those APIs are undefined. The `<TableHeader />` component you're trying to render [references `document` a few times](https://github.com/ElemeFE/element-react/blob/master/src/table/TableHeader.jsx) and isn't suitable for SSR. There are a few [open issues](https://github.com/ElemeFE/element-react/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+server) on that project already about server rendering support, so you can leave a comment on one of those if you'd like the maintainers to add it. Otherwise I'd suggest you find another UI library.

**Comment by seraj** [comment]
hi @cullenjett
thank i worked on it and fix it
i just had a another issue with run server
```
Invariant Violation: Browser history needs a DOM
    at invariant (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/invariant/invariant.js:40:15)
    at createBrowserHistory (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/history/createBrowserHistory.js:49:27)
    at new BrowserRouter (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/react-router-dom/BrowserRouter.js:46:197)
    at processChild (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:2826:14)
    at resolve (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:2792:5)
    at ReactDOMServerRenderer.render (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3172:22)
    at ReactDOMServerRenderer.read (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3131:29)
    at Object.renderToString (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:27)
    at renderToString (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/server/renderServerSideApp.js:25:33)
    at renderApp (/Users/seraj/Documents/Projects/aurorainit/hooriz-react-ssr/server/renderServerSideApp.js:20:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-ssr-boilerplate@3.0.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-ssr-boilerplate@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seraj/.npm/_logs/2019-04-16T08_50_32_982Z-debug.log
```

**Comment by cullenjett** [comment]
@seraj My guess is you've changed the code in this boilerplate and are now rendering a `<BrowserRouter />` component _somewhere_ inside  your `<App />` component rather than inside `src/main.js`. `<BrowserRouter />` is only suitable for client-side code and cannot be rendered on the server, which is why this project leaves it outside of `<App />` and uses a `<StaticRouter />` component instead (see `server/renderServerSideApp`).
