### ISSUE TITLE
Help with importing styles as modules and using their classes directly

### ISSUE THREAD

**Issue by ebrearley** [cullenjett/react-ssr-boilerplate#3]
Hey Cullen,

I've been trying to import styles as a module so I can use classes directly in the JSX. I also want to enable postcss modules (although enabling postcss modules is trivial once I get styles resolving as modules - so let's not worry about postcss-modules here). BUT for the life of me, I can't figure out why it isn't working or what I need to do to get it working. I'm hoping maybe you can help!

I'm asking you because this is something I often do most of my projects. It works perfectly everywhere, just not in your boilerplate - which I'd like to use because it should save me the time you've invested in putting this together.

This is what i'm trying to do:

Create an `about.scss` file in the components directory.
```scss
// components/about.scss
.title {
  background-color: purple;
}
```

and use the `title` class like this:
```diff
// components/About.js
import React, { Component } from 'react';
+ import styles from './about.scss'

class About extends Component {
  render() {
    return (
-      <div>
+      <div className={styles.title}>
        <h1>About page</h1>
      </div>
    );
  }
}

export default About;
```

This is where it all falls apart. I get the following output when trying to run it in development mode:
```sh
SyntaxError: ~/sites/test-project/src/pages/about/styles.scss: Unexpected token (1:0)
> 1 | .title {
    | ^
  2 |   background-color: tomato
  3 | }
    at Parser.pp$5.raise (~/sites/test-project/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (~/sites/test-project/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (~/sites/test-project/node_modules/babylon/lib/index.js:3750:12)
    at Parser.parseExprAtom (~/sites/test-project/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (~/sites/test-project/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (~/sites/test-project/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (~/sites/test-project/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (~/sites/test-project/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (~/sites/test-project/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (~/sites/test-project/node_modules/babylon/lib/index.js:6474:20)
    at Parser.pp$3.parseExpression (~/sites/test-project/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (~/sites/test-project/node_modules/babylon/lib/index.js:1906:19)
    at Parser.parseStatement (~/sites/test-project/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (~/sites/test-project/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (~/sites/test-project/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (~/sites/test-project/node_modules/babylon/lib/index.js:1673:17)
```
The reason I included the entire stack trace is because it seems to indicate that the `.scss` has been picked up by the `babel-loader`.

A normal build completes, but it doesn't include the contents of `about.scss` in the built output `css` file.

Your webpack configuration looks fine to me, with this rule:
```js
// webpack.config.dev.js
{
  test: /\.s?css$/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: {
        importLoaders: 1
      }
    },
    {
      loader: 'postcss-loader',
      options: {
        ident: 'postcss',
        plugins: () => [
          require('postcss-flexbugs-fixes'),
          autoprefixer({
            browsers: ['last 2 versions', 'not ie < 11'],
            flexbox: 'no-2009'
          })
        ]
      }
    },
    'sass-loader',
  ]
},
``` 
being all I should need to be able to import styles in the way I'm trying to.

I've tried just about every variation on the styles config from every GitHub issue and medium article i could find. I've tried adding ExtractTextWebpackPlugin to shoot for the css-modules goal and copying across Webpack config from other projects where this functionality is working. All to no avail. So I'm at a bit of a loss.

Curiously, when I use a webpack rule like this:
```js
// webpack.config.dev.js
{
  test: /\.scss$/,
  exclude: /node_modules/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [{
      loader: 'css-loader',
      query: {
          modules: true,
          sourceMap: true,
          importLoaders: 2,
          localIdentName: '[name]__[local]___[hash:base64:5]'
        }
      },
      'sass-loader',
    ]
  }),
},
```
without adding the `new ExtractTextPlugin(...)` plugin requirement, the loader doesn't bail with a `"extract-text-webpack-plugin" loader is used without the corresponding plugin` error which makes me feel like that the `.scss` loader isn't being used for the styles at all. I've tried re-ordering the loader rules and drastically simplifying the config - still no cigar.

Any ideas?

**Comment by cullenjett** [comment]
First things first, killer issue writeup. I appreciate the detail and clarity 👏.

Unfortunately, I have some bad news for you -- my gut instinct is that CSS Modules won't work with the current architecture of this project. Your Webpack config looks spot on and almost certainly works in client-side-only apps as well as SSR apps that bundle the server code, but this project doesn't bundle the server code (yet). 

Instead, it does something that's probably a little dirty and uses babel-register so that ES6 modules/JSX/etc. work on the server (see `scripts/start.js` and `server/index.js`). When babel-register gets to your `import styles from './about.scss'` line it doesn't know what to do with it, so it bails.

In an ideal world the server code would be run through Webpack and would generate it's own bundle, but this project just isn't there yet.

**Comment by arjunskumar47** [comment]
Hey,
@ebrearley , I've to really appreciate the clarity in the issue write up.
@cullenjett , This is a neat boilerplate that I end up using for almost everytime when I need to start something quickly. Thanks. 

I was looking into extending the boilerplate ( I customized the folder structure a bit ) to add CSS Modules support to it. 
I came across this babel plugin [babel-plugin-css-modules-transform](https://www.npmjs.com/package/babel-plugin-css-modules-transform), from [this article](https://medium.com/@mattvagni/server-side-rendering-with-css-modules-6b02f1238eb1). 

Do you think this is a feasible approach to add CSS Modules support to the boilerplate during SSR which can possibly avoid creating webpack bundle for server?

**Comment by cullenjett** [comment]
@arjunskumar47 I'm super glad to hear this project has been helpful! 

That babel plugin definitely sounds like it could work. I'll give it a try when I get some time (it'll be a few weeks honestly, preparing for a big release at work). Here are some things to consider in the meantime for you to get your dev build working:

- That plugin will probably need to be added to the babel register call inside `scripts/start.js` (and maybe not at all in the `.babelrc`).
- I imagine getting the generated class names to match on server and client might take a little configuration on one side (or both) -- so inside the webpack config for `css-loader` and/or in configuring the plugin added to babel register.

**Comment by arjunskumar47** [comment]
Thanks for the update! If I'm able to implement this properly, I can raise a PR. Will look into setting it up this weekend.

> That plugin will probably need to be added to the babel register call inside scripts/start.js (and maybe not at all in the .babelrc).

This was spot on. It worked!

I have to validate the class names generated on SSR and CSR are matching.

**Comment by cullenjett** [comment]
I just pushed v2.7.0 that adds support for CSS modules using the babel plugin we discussed, thanks for the idea @arjunskumar47

**Comment by arjunskumar47** [comment]
@cullenjett Awesome mate! Will test it out!
